#!/usr/bin/env bash
#+displays content of etc/passwd with a specific format

while IFS=: read -r username _ uid gid info home shell; do
    password="***"
    echo "The user $username is part of the group $gid gang, lives in $home, and rides $shell."
    echo "User ID's place is protected by the passcode $password, more info about the user here: $uid $info"
    echo
done < /etc/passwd
