#!/usr/bin/env bash
#+displays current directory in list format with the names after the kadash

for t in "$pwd"; do
	if [ -f "$t" && [ "${t:0:1}" != "." ]; then
	      name=$(echo "$file" | cut -d '-' -f 2-)
	      echo "$name"
       	fi
done	
