#!/usr/bin/env bash
#+gives info about a school file

for file in *; do
if [ -e "$file" ]; then
	echo "school file exists"
	if [ -s "$file" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f "$file" ]; then
		echo "school file is a regular file"
	fi

else
	echo "school file does not exist"
fi
done
